# Generated by Django 5.1.4 on 2025-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.CharField(max_length=50)),
                ('health', models.IntegerField()),
                ('defender', models.CharField(max_length=50)),
            ],
        ),
    ]
