# Generated by Django 5.1.4 on 2025-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='spell',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
