# Generated by Django 5.1.4 on 2025-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0002_journal_spell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_health', models.IntegerField()),
                ('cur_health', models.IntegerField()),
                ('initiative', models.IntegerField(default=1)),
            ],
        ),
    ]
