# Generated by Django 5.1.4 on 2025-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0003_enemie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('all_damage', models.IntegerField(default=0)),
                ('all_health', models.IntegerField(default=0)),
                ('count_of_moves', models.IntegerField(default=0)),
            ],
        ),
    ]
