# Generated by Django 5.1.4 on 2025-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0005_enemie_id_of_fight_journal_id_of_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
