# Generated by Django 5.1.4 on 2025-01-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0006_fight_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='slug',
        ),
    ]
