# Generated by Django 5.1.4 on 2025-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0009_journal_id_of_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
