# Generated by Django 5.1.4 on 2025-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0010_fight_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
