# Generated by Django 5.1.4 on 2025-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0011_fight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemie',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
