# Generated by Django 5.1.4 on 2025-01-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0012_enemie_is_dead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_value', models.IntegerField(default=10)),
                ('id_of_person', models.IntegerField(default=0, null=True)),
                ('is_enemies_initiative', models.BooleanField(default=False)),
                ('id_of_fight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fighting.fight')),
            ],
        ),
    ]
