# Generated by Django 5.1.4 on 2025-01-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0013_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_damage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Initiative',
        ),
    ]
