# Generated by Django 5.1.4 on 2025-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting', '0014_journal_is_damage_journal_note_delete_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='health',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
