# Generated by Django 5.1.4 on 2025-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cur_health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='character_images/f0c76a8e2cefa7c75ff4328ec491659b_LNOTyCL.jpg', null=True, upload_to='character_images'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(),
        ),
    ]
