# Generated by Django 5.1.4 on 2025-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_character_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cur_health',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=10),
        ),
    ]
